development:
  adapter: mysql2
  encoding: utf8
  database: transit_rails_development
  pool: 5
  timeout: 5000
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  database: transit_rails_test
  pool: 5
  timeout: 5000
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  database: db/transit_rails_production
  pool: 5
  timeout: 5000
