development:
  adapter: mysql2
  database: db/development.mysql
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: db/test.mysql
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: db/production.mysql
  pool: 5
  timeout: 5000
